stages:
  - lint

eslint:
  stage: lint
  image: 14.17.0-alpine
  script:
    - npm install
    - npm run lint

prettier:
  stage: lint
  image: 14.17.0-alpine
  script:
    - npm install
    - npm run check:format