name: eslint

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - name: Install nvm commands
        run: ". ~/.nvm/nvm.sh"
      - name: Install Node.js
        env:
          NODE_VERSION: 14.17.0
        run: nvm install $NODE_VERSION
      - name: Install dependencies
        run: npm install
      - name: Lint source code with ESlint
        run: npm run lint
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - name: Install nvm commands
        run: ". ~/.nvm/nvm.sh"
      - name: Install Node.js
        env:
          NODE_VERSION: 14.17.0
        run: nvm install $NODE_VERSION
      - name: Install dependencies
        run: npm install
      - name: Format source code with prettier
        run: npm run lint
